In [68]:
%run ../src/ingestion.py

Processing: Zerdab...
Processing: Quba...
Processing: Lenkeran...
Processing: Baki...
Processing: Saatli...
✅ Zerdab: 17 rows saved to zerdab_inference.parquet
✅ Quba: 17 rows saved to quba_inference.parquet
✅ Lenkeran: 17 rows saved to lenkeran_inference.parquet
✅ Baki: 17 rows saved to baki_inference.parquet
✅ Saatli: 17 rows saved to saatli_inference.parquet

✅ Data successfully collected and saved to Parquet using config settings.
Start Date: 2026-04-14
End Date: 2026-04-23

In [69]:
%run ../src/database.py

In [70]:
%run ../notebooks/day_03_database.ipynb
#olmasada olar

✅ Schemas created, tables defined, and raw data loaded successfully!
--- 1. Row Counts per City ---

       city  total_rows
0    Zerdab          17
1      Baki          17
2  Lenkeran          17
3      Quba          17
4    Saatli          17

--- 2. Date Range Verification ---

       city start_date   end_date
0  Lenkeran 2026-04-14 2026-04-30
1      Quba 2026-04-14 2026-04-30
2    Saatli 2026-04-14 2026-04-30
3      Baki 2026-04-14 2026-04-30
4    Zerdab 2026-04-14 2026-04-30

--- 3. Duplicate Checks ---
✅ PASS: No duplicate date-city combinations found.

--- 4. Data Type Verification ---

                       column_name column_type
0                             city     VARCHAR
1                             date   TIMESTAMP
2              temperature_2m_mean      DOUBLE
3   et0_fao_evapotranspiration_sum      DOUBLE
4                sunshine_duration      DOUBLE
5          shortwave_radiation_sum      DOUBLE
6        relative_humidity_2m_mean      DOUBLE
7            surface_pressure_mean      DOUBLE
8                precipitation_sum      DOUBLE
9              precipitation_hours      DOUBLE
10              wind_speed_10m_max      DOUBLE
11                cloud_cover_mean      DOUBLE
12             wind_gusts_10m_mean      DOUBLE
13     soil_moisture_0_to_7cm_mean      DOUBLE
14                       data_type     VARCHAR

--- Average Temperature per City per Year ---

       city  year  avg_temp
0      Baki  2026     12.81
1  Lenkeran  2026     13.62
2      Quba  2026      7.95
3    Saatli  2026     14.17
4    Zerdab  2026     14.54

--- Highest Variance in Daily Precipitation ---

     city  precip_variance
0  Saatli           16.159

--- Top 10 Hottest Days ---

       city exact_date  temperature_2m_mean
0    Zerdab 2026-04-27            17.952332
1    Saatli 2026-04-27            17.385168
2    Zerdab 2026-04-19            16.541666
3    Saatli 2026-04-19            16.497917
4    Zerdab 2026-04-23            16.418751
5    Zerdab 2026-04-30            16.089334
6    Saatli 2026-04-30            15.994416
7    Zerdab 2026-04-25            15.860668
8  Lenkeran 2026-04-20            15.713666
9    Zerdab 2026-04-20            15.597917

--- Days with Zero Precipitation per City per Year ---

       city  year  zero_precip_days
0    Zerdab  2026              11.0
1  Lenkeran  2026              10.0
2      Baki  2026               9.0
3    Saatli  2026               9.0
4      Quba  2026               5.0

,city,date,temperature_2m_mean,et0_fao_evapotranspiration_sum,sunshine_duration,shortwave_radiation_sum,relative_humidity_2m_mean,surface_pressure_mean,precipitation_sum,precipitation_hours,wind_speed_10m_max,cloud_cover_mean,wind_gusts_10m_mean,soil_moisture_0_to_7cm_mean,data_type
0,Baki,2026-04-14,11.312499,2.305472,33141.066406,15.010000,79.314529,1021.701904,2.4,13.0,15.856354,79.000000,22.964998,0.283333,historical
1,Baki,2026-04-15,11.702085,3.136395,41735.414062,20.240000,69.572823,1024.161987,0.3,3.0,15.484185,47.250000,28.199997,0.277208,historical
2,Baki,2026-04-16,13.097917,3.106966,42755.191406,19.440001,65.637993,1023.956787,0.0,0.0,12.362475,20.416666,14.085001,0.260625,historical
3,Baki,2026-04-17,12.995834,3.021810,42742.210938,21.790001,80.436111,1024.379028,0.0,0.0,16.036171,22.750000,25.874998,0.239250,historical
4,Baki,2026-04-18,13.668750,2.861732,43815.843750,22.580000,83.649406,1016.915588,0.0,0.0,22.350464,27.541666,38.280003,0.212958,historical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Zerdab,2026-04-26,14.039833,3.082464,29227.609375,17.500000,68.958336,1020.760742,0.0,0.0,19.576189,85.791664,17.445000,NaN,forecast
81,Zerdab,2026-04-27,17.952332,5.028692,45515.457031,23.530001,60.458332,1010.165833,0.0,0.0,24.633049,83.708336,23.984999,NaN,forecast
82,Zerdab,2026-04-28,15.491916,3.685580,16628.697266,10.940000,50.041668,1019.290955,0.0,0.0,26.980793,88.125000,35.595001,NaN,forecast
83,Zerdab,2026-04-29,12.838752,2.393121,16414.091797,13.720000,56.489582,1022.086243,0.0,0.0,6.193674,90.375000,8.827499,NaN,forecast
84,Zerdab,2026-04-30,16.089334,3.796965,40196.617188,22.350000,62.875000,1018.006104,0.0,0.0,5.634891,78.500000,8.579999,NaN,forecast

In [71]:
import duckdb

#database.py-də təyin etdiyin yola uyğun qoşuluruq
conn = duckdb.connect('../data/weather_pipeline.duckdb')

In [72]:
# 1. Create connection
conn = get_connection()

# 2. Set up the database (schemas and tables) from scratch
create_schemas(conn)
create_raw_tables(conn)

# 3. Now load data from parquet files
load_raw_data(conn)

print("Database is ready and data has been loaded!")

Database is ready and data has been loaded!

In [73]:
%run ../src/cleaning.py

In [74]:
%run ../src/features.py
created_features_df=create_features(conn)

🔧 Generating features from staging.weather_daily ...
✅ Features computed: day_of_year, precip_sum_7d, prev_soil_moisture

Data now has 85 rows and 18 columns.

📊 Example of engineered data:
city       date  temperature_2m_mean  et0_fao_evapotranspiration_sum  sunshine_duration  shortwave_radiation_sum  relative_humidity_2m_mean  surface_pressure_mean  precipitation_sum  precipitation_hours  wind_speed_10m_max  cloud_cover_mean  wind_gusts_10m_mean  soil_moisture_0_to_7cm_mean  data_type  day_of_year  precip_sum_7d  prev_soil_moisture
Baki 2026-04-14            11.312499                        2.305472       33141.066406                15.010000                  79.314529            1021.701904                2.4                 13.0           15.856354         79.000000            22.964998                     0.283333 historical          104            2.4                 NaN
Baki 2026-04-15            11.702085                        3.136395       41735.414062                20.240000                  69.572823            1024.161987                0.3                  3.0           15.484185         47.250000            28.199997                     0.277208 historical          105            2.7            0.283333
Baki 2026-04-16            13.097917                        3.106966       42755.191406                19.440001                  65.637993            1023.956787                0.0                  0.0           12.362475         20.416666            14.085001                     0.260625 historical          106            2.7            0.277208
Baki 2026-04-17            12.995834                        3.021810       42742.210938                21.790001                  80.436111            1024.379028                0.0                  0.0           16.036171         22.750000            25.874998                     0.239250 historical          107            2.7            0.260625
Baki 2026-04-18            13.668750                        2.861732       43815.843750                22.580000                  83.649406            1016.915588                0.0                  0.0           22.350464         27.541666            38.280003                     0.212958 historical          108            2.7            0.239250
Baki 2026-04-19            15.177083                        3.267373       41231.125000                21.450001                  80.289223            1006.191345                0.1                  1.0           20.803045         51.625000            34.079998                     0.188708 historical          109            2.8            0.212958
Baki 2026-04-20            13.847917                        2.064010        8520.239258                 9.200000                  76.577911            1011.642517                1.8                  6.0           24.725605         95.208336            47.235001                     0.188417 historical          110            4.6            0.188708
Baki 2026-04-21            10.787499                        1.553613       13218.458984                 9.220000                  83.323708            1015.477234                6.4                 11.0           22.158285         75.750000            38.565002                     0.244083 historical          111            8.6            0.188417
Baki 2026-04-22            13.112499                        3.127617       43021.062500                20.930000                  80.909668            1013.233398                0.0                  0.0           18.501513         51.833332            25.094997                     0.240625 historical          112            8.3            0.244083
Baki 2026-04-23            12.887501                        1.882021       21648.394531                13.040000                  86.022186            1011.448242                0.1                  1.0           19.380743         58.000000            29.189997                     0.225250 historical          113            8.4            0.240625

✅ Features written to analytics.weather_features.

In [75]:
created_features_df

,city,date,temperature_2m_mean,et0_fao_evapotranspiration_sum,sunshine_duration,shortwave_radiation_sum,relative_humidity_2m_mean,surface_pressure_mean,precipitation_sum,precipitation_hours,wind_speed_10m_max,cloud_cover_mean,wind_gusts_10m_mean,soil_moisture_0_to_7cm_mean,data_type,day_of_year,precip_sum_7d,prev_soil_moisture
0,Baki,2026-04-14,11.312499,2.305472,33141.066406,15.010000,79.314529,1021.701904,2.4,13.0,15.856354,79.000000,22.964998,0.283333,historical,104,2.4,NaN
1,Baki,2026-04-15,11.702085,3.136395,41735.414062,20.240000,69.572823,1024.161987,0.3,3.0,15.484185,47.250000,28.199997,0.277208,historical,105,2.7,0.283333
2,Baki,2026-04-16,13.097917,3.106966,42755.191406,19.440001,65.637993,1023.956787,0.0,0.0,12.362475,20.416666,14.085001,0.260625,historical,106,2.7,0.277208
3,Baki,2026-04-17,12.995834,3.021810,42742.210938,21.790001,80.436111,1024.379028,0.0,0.0,16.036171,22.750000,25.874998,0.239250,historical,107,2.7,0.260625
4,Baki,2026-04-18,13.668750,2.861732,43815.843750,22.580000,83.649406,1016.915588,0.0,0.0,22.350464,27.541666,38.280003,0.212958,historical,108,2.7,0.239250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Zerdab,2026-04-26,14.039833,3.082464,29227.609375,17.500000,68.958336,1020.760742,0.0,0.0,19.576189,85.791664,17.445000,NaN,forecast,116,15.0,NaN
81,Zerdab,2026-04-27,17.952332,5.028692,45515.457031,23.530001,60.458332,1010.165833,0.0,0.0,24.633049,83.708336,23.984999,NaN,forecast,117,11.6,NaN
82,Zerdab,2026-04-28,15.491916,3.685580,16628.697266,10.940000,50.041668,1019.290955,0.0,0.0,26.980793,88.125000,35.595001,NaN,forecast,118,0.1,NaN
83,Zerdab,2026-04-29,12.838752,2.393121,16414.091797,13.720000,56.489582,1022.086243,0.0,0.0,6.193674,90.375000,8.827499,NaN,forecast,119,0.1,NaN
84,Zerdab,2026-04-30,16.089334,3.796965,40196.617188,22.350000,62.875000,1018.006104,0.0,0.0,5.634891,78.500000,8.579999,NaN,forecast,120,0.0,NaN

In [76]:
city_stats = conn.execute("""
    SELECT city, COUNT(*) as row_count, MIN(date) as start_date, MAX(date) as end_date 
    FROM raw.weather_daily 
    GROUP BY city
""").df()
display(city_stats)

       city  row_count start_date   end_date
0      Baki         17 2026-04-14 2026-04-30
1    Saatli         17 2026-04-14 2026-04-30
2    Zerdab         17 2026-04-14 2026-04-30
3  Lenkeran         17 2026-04-14 2026-04-30
4      Quba         17 2026-04-14 2026-04-30

In [55]:
conn.close()